name: CompileTest


on:
  pull_request:
    branches: [master, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: gw_analysis_tools
      - uses: actions/checkout@v4
        with:
          repository: bayescollab/BayesShip
          path: BayesShip
      - name: Set up Container Stuff
        run: |
          docker build -t gwatubuntu -f gw_analysis_tools/docker_files/Dockerfile.gwatubuntu .
          docker build --target bayes-build -t gwat_dev -f gw_analysis_tools/docker_files/Dockerfile.gwat.bayesship .
          docker run --rm --mount type=bind,source=$GITHUB_WORKSPACE/gw_analysis_tools,target="/opt/gw_analysis_tools" gwat_dev bash -c "
            cd build || (mkdir build && cd build) && \
            rm -rf * && \
            cmake -DCMAKE_INSTALL_PREFIX=/usr/local ../ && \
            make -j 4 && make install
          "